"""Write docs/example_prompt.md from a logged LLM call of a finished run (no API call).

    python scripts/make_example_prompt.py [--run runs/L-clock_mock_py_s1] [--day 11] [--agent ID]

The user message is copied verbatim from llm_calls.jsonl (the first T2 wake on --day with a car
as the usual choice and, when there is one, the employer's early-start permission, unless --agent
is given); the system prompt, schema and request are rebuilt
with cordonlite.llm from the run's config snapshot.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from cordonlite import llm  # noqa: E402
from cordonlite.config import load_config  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default=str(ROOT / "runs" / "L-clock_mock_py_s1"))
    ap.add_argument("--day", type=int, default=11)
    ap.add_argument("--agent", type=int, default=None)
    ap.add_argument("--out", default=str(ROOT / "docs" / "example_prompt.md"))
    a = ap.parse_args()
    run = Path(a.run)
    cfg = load_config(run / "config_snapshot.toml")
    recs = [json.loads(x) for x in (run / "llm_calls.jsonl").read_text().splitlines()]
    cand = [r for r in recs if r["day"] == a.day and (a.agent is None or r["agent_id"] == a.agent)]
    if a.agent is None:
        cand = [r for r in cand if "Your usual choice lately: drive" in r["user"]] or cand
        # prefer a commuter whose employer allows the early start, so the example shows that sentence
        cand = [r for r in cand if "Your employer lets you work" in r["user"]] or cand
    r = cand[0]
    system = llm.system_prompt(cfg)
    schema = llm.output_schema(r["schema_option_ids"])
    req = llm.AnthropicLLM(cfg, client=object()).build_request("<SYSTEM PROMPT above>", "<USER MESSAGE above>", schema)
    chars = len(system) + len(r["user"])
    md = [
        "# Example rendered prompt (template `cl-v1`)",
        "",
        f"Generated by `scripts/make_example_prompt.py` from `{run.relative_to(ROOT) if run.is_relative_to(ROOT) else run}`, "
        f"agent {r['agent_id']}, day {r['day']} (triggers: {', '.join(r['triggers']) or 'none'}). The user "
        "message is copied verbatim from `llm_calls.jsonl`; no API call was made. The run used the "
        "MockLLM backend, so the answer at the end is the deterministic stand-in, not a model reply.",
        "",
        "Neither the archetype nor the trait names nor the generalised cost (GC) appear in the prompt. "
        "Work and study are described by the same constraint sentences, and start-time flexibility "
        "is graded in four steps that follow the rule's schedule-delay multiplier. This commuter's "
        "employer allows the earlier working day, so the situation states it and the `start time` column "
        "shows which start each option is measured against.",
        "",
        f"Prompt size: {chars} characters, about {round(chars / 4)} tokens (approximate: characters / 4; "
        "excludes the schema and the output). Count it as uncached input: the system prompt is below "
        "the minimum cacheable prefix and the schema differs per agent.",
        "",
        "## System prompt", "", "```text", system, "```", "",
        "## User message", "", "```text", r["user"].rstrip("\n"), "```", "",
        "## Output schema (`output_config.format.schema`)", "",
        "The `choice` enum is this agent's feasible option ids for today. `reason` comes first so that "
        "it is written before the choice.", "", "```json", json.dumps(schema, indent=2), "```", "",
        "## Request sent to the Messages API", "",
        "`AnthropicLLM.build_request` builds this request. With `use_fallbacks = true` it is sent "
        "through `client.beta.messages.create`; otherwise through `client.messages.create` without "
        "`betas` and `fallbacks`. No sampling parameters are sent. Thinking is left at the model "
        "default, which is adaptive on `claude-opus-5-5`.", "",
        "```json", json.dumps(req, indent=2), "```", "",
        "## Logged answer (MockLLM)", "", "```json", json.dumps(r["parsed"], indent=2), "```", "",
    ]
    Path(a.out).write_text("\n".join(md), encoding="utf-8")
    print(a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
